# Generated by Django 5.1.15 on 2026-05-09 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_score', models.FloatField(default=0.0, help_text='Similitud del coseno entre vectores musicales (0.0 a 1.0).', verbose_name='Score de compatibilidad')),
                ('status', models.CharField(choices=[('suggested', 'Sugerido'), ('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('blocked', 'Bloqueado')], default='suggested', max_length=20, verbose_name='Estado')),
                ('matched_at', models.DateTimeField(blank=True, help_text='Momento en que la relación pasó a ACCEPTED.', null=True, verbose_name='Fecha de match')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_source', to=settings.AUTH_USER_MODEL, verbose_name='Usuario (menor id)')),
                ('user_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_target', to=settings.AUTH_USER_MODEL, verbose_name='Usuario (mayor id)')),
            ],
            options={
                'verbose_name': 'Amistad / Match',
                'verbose_name_plural': 'Amistades / Matches',
                'db_table': 'encorely_friendships',
                'ordering': ['-updated_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('user_source__lt', models.F('user_target'))), name='friendship_source_lt_target'), models.UniqueConstraint(fields=('user_source', 'user_target'), name='friendship_unique_ordered_pair')],
            },
        ),
    ]
