# Generated by Django 5.1.15 on 2026-05-02 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Descripción breve sobre ti y tus gustos musicales.', max_length=500, verbose_name='Biografía'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='', help_text='Ciudad de residencia para filtrar eventos y matches cercanos.', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='user',
            name='concert_mood',
            field=models.CharField(choices=[('moshpit', '🤘 Moshpit'), ('front_row', '🎤 Front Row'), ('chiller', '😎 Chiller'), ('vip', '🥂 VIP')], default='chiller', help_text='Tu estilo preferido en conciertos.', max_length=20, verbose_name='Mood de concierto'),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, help_text='Nombre que se muestra en la app. Si está vacío, se usa el username.', max_length=100, verbose_name='Nombre de perfil'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Indica si el usuario tiene acceso a funcionalidades premium.', verbose_name='Usuario Premium'),
        ),
        migrations.AddField(
            model_name='user',
            name='swipe_count',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de canciones evaluadas. Se necesitan 25 para desbloquear el Radar.', verbose_name='Swipes realizados'),
        ),
        migrations.CreateModel(
            name='MusicVibeVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.FloatField(default=0.0, help_text='Nivel de energía musical promedio (0.0 = calmado, 1.0 = intenso).', verbose_name='Energía')),
                ('danceability', models.FloatField(default=0.0, help_text='Qué tan bailable es la música preferida (0.0 a 1.0).', verbose_name='Bailabilidad')),
                ('valence', models.FloatField(default=0.0, help_text='Positividad emocional de la música (0.0 = triste, 1.0 = alegre).', verbose_name='Valencia')),
                ('tempo', models.FloatField(default=0.0, help_text='Tempo normalizado preferido (0.0 a 1.0).', verbose_name='Tempo')),
                ('top_genres', models.JSONField(blank=True, default=list, help_text='Lista de géneros musicales más frecuentes en los swipes RIGHT.', verbose_name='Géneros favoritos')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vibe_vector', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Vector de ADN Musical',
                'verbose_name_plural': 'Vectores de ADN Musical',
                'db_table': 'encorely_vibe_vectors',
            },
        ),
    ]
