# Generated by Django 5.1.15 on 2026-05-09 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('artist_name', models.CharField(max_length=255, verbose_name='Artista')),
                ('venue_name', models.CharField(max_length=255, verbose_name='Lugar')),
                ('event_date', models.DateTimeField(verbose_name='Fecha del evento')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('affiliate_url', models.URLField(blank=True, default='', verbose_name='URL afiliado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'encorely_events',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_ticket', models.BooleanField(default=False, verbose_name='Tiene entrada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.event', verbose_name='Evento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Asistencia a evento',
                'verbose_name_plural': 'Asistencias a eventos',
                'db_table': 'encorely_event_attendance',
                'constraints': [models.UniqueConstraint(fields=('user', 'event'), name='event_attendance_unique_user_event')],
            },
        ),
    ]
