# Generated by Django 5.1.15 on 2026-05-09 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friendship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='matches.friendship', verbose_name='Amistad')),
            ],
            options={
                'verbose_name': 'Sala de chat',
                'verbose_name_plural': 'Salas de chat',
                'db_table': 'encorely_chat_rooms',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leído')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom', verbose_name='Sala')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages_sent', to=settings.AUTH_USER_MODEL, verbose_name='Remitente')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'db_table': 'encorely_messages',
                'ordering': ['sent_at'],
            },
        ),
    ]
