# Generated by Django 5.1.15 on 2026-05-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("energy", models.FloatField(default=0.0, verbose_name="Energía")),
                (
                    "danceability",
                    models.FloatField(default=0.0, verbose_name="Bailabilidad"),
                ),
                ("valence", models.FloatField(default=0.0, verbose_name="Valencia")),
                ("tempo", models.FloatField(default=0.0, verbose_name="Tempo")),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "artist_name",
                    models.CharField(max_length=255, verbose_name="Artista"),
                ),
                (
                    "preview_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Preview URL",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="Image URL"
                    ),
                ),
            ],
            options={
                "verbose_name": "Canción",
                "verbose_name_plural": "Canciones",
                "db_table": "encorely_songs",
            },
        ),
    ]
