# Generated by Antigravity on 2026-05-09

from django.db import migrations

def seed_extra_songs(apps, schema_editor):
    Song = apps.get_model('music', 'Song')
    extra_songs = [
        {"pk": 31, "title": "As It Was", "artist_name": "Harry Styles", "energy": 0.7, "danceability": 0.6, "valence": 0.6, "tempo": 0.7, "image_url": "https://i.scdn.co/image/ab67616d0000b273b46f74097655d7f353caab14"},
        {"pk": 32, "title": "Heat Waves", "artist_name": "Glass Animals", "energy": 0.5, "danceability": 0.7, "valence": 0.5, "tempo": 0.3, "image_url": "https://i.scdn.co/image/ab67616d0000b2739eb29976378e9fde978cf674"},
        {"pk": 33, "title": "Save Your Tears", "artist_name": "The Weeknd", "energy": 0.8, "danceability": 0.6, "valence": 0.6, "tempo": 0.5, "image_url": "https://i.scdn.co/image/ab67616d0000b2738863bc98b23f2c9cb28fe9ae"},
        {"pk": 34, "title": "Stay", "artist_name": "The Kid LAROI", "energy": 0.7, "danceability": 0.6, "valence": 0.4, "tempo": 0.8, "image_url": "https://i.scdn.co/image/ab67616d0000b273f55f3e3e3e3e3e3e3e3e3e3e"},
        {"pk": 35, "title": "Flowers", "artist_name": "Miley Cyrus", "energy": 0.6, "danceability": 0.7, "valence": 0.6, "tempo": 0.5, "image_url": "https://i.scdn.co/image/ab67616d0000b273f7f7f7f7f7f7f7f7f7f7f7f7"},
        {"pk": 36, "title": "Anti-Hero", "artist_name": "Taylor Swift", "energy": 0.6, "danceability": 0.6, "valence": 0.5, "tempo": 0.4, "image_url": "https://i.scdn.co/image/ab67616d0000b273bbbbbbbbbbbbbbbbbbbbbbbb"},
        {"pk": 37, "title": "Kill Bill", "artist_name": "SZA", "energy": 0.7, "danceability": 0.6, "valence": 0.4, "tempo": 0.4, "image_url": "https://i.scdn.co/image/ab67616d0000b273cccccccccccccccccccccccc"},
        {"pk": 38, "title": "Creepin'", "artist_name": "Metro Boomin", "energy": 0.6, "danceability": 0.7, "valence": 0.2, "tempo": 0.4, "image_url": "https://i.scdn.co/image/ab67616d0000b273dddddddddddddddddddddddd"},
        {"pk": 39, "title": "Die For You", "artist_name": "The Weeknd", "energy": 0.5, "danceability": 0.6, "valence": 0.5, "tempo": 0.6, "image_url": "https://i.scdn.co/image/ab67616d0000b2738863bc98b23f2c9cb28fe9ae"},
        {"pk": 40, "title": "Starboy", "artist_name": "The Weeknd", "energy": 0.8, "danceability": 0.6, "valence": 0.4, "tempo": 0.9, "image_url": "https://i.scdn.co/image/ab67616d0000b2734718e2b124f79258be7bc452"},
    ]
    for data in extra_songs:
        Song.objects.get_or_create(id=data['pk'], defaults={
            'title': data['title'],
            'artist_name': data['artist_name'],
            'energy': data['energy'],
            'danceability': data['danceability'],
            'valence': data['valence'],
            'tempo': data['tempo'],
            'image_url': data['image_url'],
        })

class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_swipe'),
    ]

    operations = [
        migrations.RunPython(seed_extra_songs),
    ]
